### ISSUE TITLE
感谢大佬做的插件，非常好用，给一点小提议。

### ISSUE THREAD

**Issue by EAloo** [half-ghost/steam_crawler_bot#1]
想问一下 能不能新增 可以查询历史新低的功能。
另外能否有 限时免费的标签 或者 喜加1的呢？

**Comment by half-ghost** [comment]
唔，据我玩steam这么久来说，好像没有见过steam有可以直接看新史低的链接，不过这个插件本质上是个爬虫，我记得其他网站有些是可以看新史地的，这是个好提议，我会在后边找时间加进去。限免的标签我记得st是有链接的，后边也会再开发加进去

**Comment by half-ghost** [comment]
写完了查询史低的功能了，喜加一功能本来想从steamdb上爬的，奈何steamdb的反爬虫机制以我现在的技术力还难以破解，故放弃。如果有什么更好的喜加一数据源的话可以告知我，我会试着用爬虫爬下来的
