### ISSUE TITLE
出事了，这个插件会在晚上0点之前使机器人停止运行

### ISSUE THREAD

**Issue by 1055169799** [half-ghost/steam_crawler_bot#2]
好像是插件里的时间出问题了，今年频发，之前我也不敢确定，但是停用了这个插件之后就没事了。 后来我看到了其他人的，发现确实是这个问题。https://github.com/Soung2279/haru-bot-setup/issues/5

**Comment by half-ghost** [comment]
这个bot里用的是我7个月前的代码，速速更新最新版本！(敲头)
